# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mydriver.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
from matplotlib.backends.backend_qt5agg import FigureCanvasQTAgg as FigureCanvas
from matplotlib.figure import Figure



class MplCanvas(FigureCanvas):
    def __init__(self, parent=None, width=5, height=4, dpi=1000):
        fig = Figure(figsize=(width, height), dpi=dpi)
        self.axes = fig.add_subplot(111)
        self.axes.get_yaxis().set_visible(False)
        self.axes.get_xaxis().set_visible(False)
        self.axes.set(facecolor="white")
        fig.subplots_adjust(left=0.02, right=0.98, top=0.98, bottom=0.02)
        fig.set_facecolor('white')
        super(MplCanvas, self).__init__(fig)


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1800, 1120)
        self.face_mesh = QtWidgets.QLabel(Form)
        self.face_mesh.setGeometry(QtCore.QRect(15, 10, 520, 400))
        self.face_mesh.setFrameShape(QtWidgets.QFrame.Box)
        self.face_mesh.setFrameShadow(QtWidgets.QFrame.Plain)
        self.face_mesh.setText("")
        self.face_mesh.setObjectName("face_mesh")
        self.camera_show = QtWidgets.QLabel(Form)
        self.camera_show.setGeometry(QtCore.QRect(572, 136, 1200, 960))
        self.camera_show.setFrameShape(QtWidgets.QFrame.Box)
        self.camera_show.setFrameShadow(QtWidgets.QFrame.Plain)
        self.camera_show.setText("")
        self.camera_show.setObjectName("camera_show")
        self.head_pose_label = QtWidgets.QLabel(Form)
        self.head_pose_label.setGeometry(QtCore.QRect(20, 440, 540, 60))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.head_pose_label.setFont(font)
        self.head_pose_label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.head_pose_label.setFrameShadow(QtWidgets.QFrame.Plain)
        self.head_pose_label.setObjectName("head_pose_label")
        self.head_yaw = QtWidgets.QLineEdit(Form)
        self.head_yaw.setGeometry(QtCore.QRect(80, 500, 80, 40))
        self.head_yaw.setFrame(False)
        self.head_yaw.setObjectName("head_yaw")
        self.head_yaw_label = QtWidgets.QLabel(Form)
        self.head_yaw_label.setGeometry(QtCore.QRect(26, 500, 50, 32))
        self.head_yaw_label.setObjectName("head_yaw_label")
        self.head_pitch_label = QtWidgets.QLabel(Form)
        self.head_pitch_label.setGeometry(QtCore.QRect(200, 500, 60, 32))
        self.head_pitch_label.setObjectName("head_pitch_label")
        self.head_pitch = QtWidgets.QLineEdit(Form)
        self.head_pitch.setGeometry(QtCore.QRect(280, 500, 80, 40))
        self.head_pitch.setFrame(False)
        self.head_pitch.setObjectName("head_pitch")
        self.head_roll_label = QtWidgets.QLabel(Form)
        self.head_roll_label.setGeometry(QtCore.QRect(400, 500, 60, 32))
        self.head_roll_label.setObjectName("head_roll_label")
        self.head_roll = QtWidgets.QLineEdit(Form)
        self.head_roll.setGeometry(QtCore.QRect(460, 500, 80, 40))
        self.head_roll.setFrame(False)
        self.head_roll.setObjectName("head_roll")
        self.eye_state_label = QtWidgets.QLabel(Form)
        self.eye_state_label.setGeometry(QtCore.QRect(20, 550, 540, 60))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.eye_state_label.setFont(font)
        self.eye_state_label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.eye_state_label.setFrameShadow(QtWidgets.QFrame.Plain)
        self.eye_state_label.setObjectName("eye_state_label")
        self.left_eye = QtWidgets.QLabel(Form)
        self.left_eye.setGeometry(QtCore.QRect(20, 610, 160, 120))
        self.left_eye.setFrameShape(QtWidgets.QFrame.Box)
        self.left_eye.setFrameShadow(QtWidgets.QFrame.Plain)
        self.left_eye.setText("")
        self.left_eye.setObjectName("left_eye")
        self.right_eye = QtWidgets.QLabel(Form)
        self.right_eye.setGeometry(QtCore.QRect(200, 610, 160, 120))
        self.right_eye.setFrameShape(QtWidgets.QFrame.Box)
        self.right_eye.setFrameShadow(QtWidgets.QFrame.Plain)
        self.right_eye.setText("")
        self.right_eye.setObjectName("right_eye")
        self.mouth = QtWidgets.QLabel(Form)
        self.mouth.setGeometry(QtCore.QRect(380, 610, 176, 120))
        self.mouth.setFrameShape(QtWidgets.QFrame.Box)
        self.mouth.setFrameShadow(QtWidgets.QFrame.Plain)
        self.mouth.setText("")
        self.mouth.setObjectName("mouth")
        self.left_eye_label = QtWidgets.QLabel(Form)
        self.left_eye_label.setGeometry(QtCore.QRect(52, 740, 120, 32))
        self.left_eye_label.setObjectName("left_eye_label")
        self.right_eye_label = QtWidgets.QLabel(Form)
        self.right_eye_label.setGeometry(QtCore.QRect(222, 740, 120, 32))
        self.right_eye_label.setObjectName("right_eye_label")
        self.mouth_label = QtWidgets.QLabel(Form)
        self.mouth_label.setGeometry(QtCore.QRect(432, 740, 120, 32))
        self.mouth_label.setObjectName("mouth_label")
        self.gaze_direction_label = QtWidgets.QLabel(Form)
        self.gaze_direction_label.setGeometry(QtCore.QRect(20, 774, 540, 60))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.gaze_direction_label.setFont(font)
        self.gaze_direction_label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.gaze_direction_label.setFrameShadow(QtWidgets.QFrame.Plain)
        self.gaze_direction_label.setObjectName("gaze_direction_label")
        self.gaze_yaw_label = QtWidgets.QLabel(Form)
        self.gaze_yaw_label.setGeometry(QtCore.QRect(20, 840, 50, 32))
        self.gaze_yaw_label.setObjectName("gaze_yaw_label")
        self.blink_duration_label = QtWidgets.QLabel(Form)
        self.blink_duration_label.setGeometry(QtCore.QRect(340, 774, 220, 60))
        self.blink_duration_label.setObjectName("blink_duration_label")
        self.blink_duration_label.setFont(font)
        self.gaze_pitch = QtWidgets.QLineEdit(Form)
        self.gaze_pitch.setGeometry(QtCore.QRect(224, 836, 76, 40))
        self.gaze_pitch.setFrame(False)
        self.gaze_pitch.setObjectName("gaze_pitch")
        self.gaze_pitch_label = QtWidgets.QLabel(Form)
        self.gaze_pitch_label.setGeometry(QtCore.QRect(160, 836, 60, 32))
        self.gaze_pitch_label.setObjectName("gaze_pitch_label")
        self.gaze_yaw = QtWidgets.QLineEdit(Form)
        self.gaze_yaw.setGeometry(QtCore.QRect(70, 836, 76, 40))
        self.gaze_yaw.setFrame(False)
        self.gaze_yaw.setObjectName("gaze_yaw")
        self.blink_duration = QtWidgets.QProgressBar(Form)
        self.blink_duration.setGeometry(QtCore.QRect(340, 836, 218, 40))
        # self.blink_duration.setFrame(False)
        self.blink_duration.setRange(0, 100)
        self.blink_duration.setObjectName("blink_duration")
        self.Yawn_frequency_label = QtWidgets.QLabel(Form)
        self.Yawn_frequency_label.setGeometry(QtCore.QRect(20, 880, 260, 60))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.Yawn_frequency_label.setFont(font)
        self.Yawn_frequency_label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.Yawn_frequency_label.setFrameShadow(QtWidgets.QFrame.Plain)
        self.Yawn_frequency_label.setObjectName("Yawn_frequency_label")
        self.drowsiness_state_label = QtWidgets.QLabel(Form)
        self.drowsiness_state_label.setGeometry(QtCore.QRect(304, 880, 272, 60))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.drowsiness_state_label.setFont(font)
        self.drowsiness_state_label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.drowsiness_state_label.setFrameShadow(QtWidgets.QFrame.Plain)
        self.drowsiness_state_label.setObjectName("drowsiness_state_label")

        self.draw_figure = QtWidgets.QWidget(Form)
        self.draw_figure.setObjectName("draw_figure")
        self.draw_figure.setGeometry(QtCore.QRect(20, 940, 540, 160))
        self.hLayout = QtWidgets.QHBoxLayout(self.draw_figure)
        self.hLayout.setObjectName("hLayout")
        self.hLayout.setContentsMargins(0, 0, 0, 0)
        self.canvas1 = MplCanvas(self.draw_figure, width=2, height=1, dpi=50)
        self.canvas2 = MplCanvas(self.draw_figure, width=2, height=1, dpi=50)
        self.hLayout.addWidget(self.canvas1)
        self.hLayout.addWidget(self.canvas2)

        self.button_open_camera = QtWidgets.QPushButton(Form)
        self.button_open_camera.setGeometry(QtCore.QRect(800, 1032, 200, 50))
        self.button_open_camera.setObjectName("button_open_camera")
        self.button_close = QtWidgets.QPushButton(Form)
        self.button_close.setGeometry(QtCore.QRect(1360, 1032, 200, 50))
        self.button_close.setObjectName("button_close")

        self.drowsiness_detection_label = QtWidgets.QLabel(Form)
        self.drowsiness_detection_label.setGeometry(QtCore.QRect(572, 10, 300, 60))
        font1 = QtGui.QFont()
        font1.setFamily("Arial")
        font1.setPointSize(10)
        font1.setBold(True)
        font1.setWeight(75)
        self.drowsiness_detection_label.setFont(font1)
        self.drowsiness_detection_label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.drowsiness_detection_label.setFrameShadow(QtWidgets.QFrame.Plain)
        self.drowsiness_detection_label.setObjectName("drowsiness_detection_label")
        self.drowsiness_detection = QtWidgets.QProgressBar(Form)
        self.drowsiness_detection.setGeometry(QtCore.QRect(860, 20, 920, 40))
        self.drowsiness_detection.setRange(0, 100)
        self.drowsiness_detection.setObjectName("drowsiness_detection")

        self.distraction_detection_label = QtWidgets.QLabel(Form)
        self.distraction_detection_label.setGeometry(QtCore.QRect(572, 60, 300, 60))
        self.distraction_detection_label.setFont(font1)
        self.distraction_detection_label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.distraction_detection_label.setFrameShadow(QtWidgets.QFrame.Plain)
        self.distraction_detection_label.setObjectName("distraction_detection_label")
        self.distraction_detection = QtWidgets.QProgressBar(Form)
        self.distraction_detection.setGeometry(QtCore.QRect(860, 72, 920, 40))
        self.distraction_detection.setRange(0, 100)
        self.distraction_detection.setObjectName("distraction_detection")


        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.head_pose_label.setText(_translate("Form", "Head pose"))
        self.head_yaw_label.setText(_translate("Form", "Yaw"))
        self.head_pitch_label.setText(_translate("Form", "Pitch"))
        self.head_roll_label.setText(_translate("Form", "Roll"))
        self.eye_state_label.setText(_translate("Form", "Eyes and mouth state"))
        self.left_eye_label.setText(_translate("Form", "Left eye"))
        self.right_eye_label.setText(_translate("Form", "Right eye"))
        self.mouth_label.setText(_translate("Form", "Mouth"))
        self.gaze_direction_label.setText(_translate("Form", "Gaze direction"))
        self.gaze_yaw_label.setText(_translate("Form", "Yaw"))
        self.blink_duration_label.setText(_translate("Form", "Blink duration"))
        self.gaze_pitch_label.setText(_translate("Form", "Pitch"))
        self.Yawn_frequency_label.setText(_translate("Form", "Yawn frequency"))
        self.drowsiness_state_label.setText(_translate("Form", "Blink frequency"))
        self.drowsiness_detection_label.setText(_translate("Form", "Drowsiness detection"))
        self.distraction_detection_label.setText(_translate("Form", "Distraction detection"))
        self.button_open_camera.setText(_translate("Form", "Open Camera"))
        self.button_close.setText(_translate("Form", "Exit"))


